In [1]:
import numpy as np

In [2]:
np

<module 'numpy' from '/usr/local/python/3.14.2/lib/python3.14/site-packages/numpy/__init__.py'>

## Creating arrays

In [3]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [7]:
a = np.array([1, 2, 3, 5, 7, 12])
a

array([ 1,  2,  3,  5,  7, 12])

In [8]:
a[2]

np.int64(3)

In [9]:
a[2] = 10

In [10]:
a

array([ 1,  2, 10,  5,  7, 12])

In [11]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [14]:
np.linspace(0, 1, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

## Multi-dimensional arrays

In [15]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [16]:
np.array([[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
n = np.array([[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]])
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
n[0, 1]

np.int64(2)

In [19]:
n[0, 1] = 10
n

array([[ 1, 10,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [20]:
n[0]

array([ 1, 10,  3])

In [21]:
n[2] = [1, 1, 1]
n

array([[ 1, 10,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [22]:
n[:, 1]

array([10,  5,  1])

## Randomly generated arrays

In [26]:
np.random.rand(5, 2)

array([[0.01753379, 0.77288585],
       [0.51817644, 0.01808924],
       [0.78765104, 0.2763174 ],
       [0.09707804, 0.23623363],
       [0.6506877 , 0.05510143]])

In [27]:
np.random.seed(2)
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [28]:
np.random.seed(2)
np.random.randn(5,2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [30]:
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5, 2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

## Element-wise operations

In [31]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [32]:
a + 1

array([1, 2, 3, 4, 5])

In [33]:
a * 2

array([0, 2, 4, 6, 8])

In [35]:
b = (10 + (a * 2))**2 / 100
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [36]:
a + b

array([1.  , 2.44, 3.96, 5.56, 7.24])

## Comparison operations

In [37]:
a >= 2

array([False, False,  True,  True,  True])

In [38]:
a > b

array([False, False,  True,  True,  True])

In [40]:
a[a>b]

array([2, 3, 4])

## Summarizing operations

In [41]:
a.min()

np.int64(0)

In [42]:
a.max()

np.int64(4)

In [43]:
a.sum()

np.int64(10)

In [45]:
a.mean()

np.float64(2.0)

In [46]:
a.std()

np.float64(1.4142135623730951)